services:
  nginx:
    image: nginx:latest
    container_name: ${APP_PREFIX}_nginx
    hostname: ${APP_PREFIX}_nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mariadb

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_PREFIX}_php
    hostname: ${APP_PREFIX}_php
    volumes:
      - ./:/app
      - ./docker/ssh:/root/.ssh/
      - ./docker/git/.gitconfig:/root/.gitconfig
    working_dir: /app/code
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    image: mariadb:latest
    container_name: ${APP_PREFIX}_mariadb
    hostname: ${APP_PREFIX}_mariadb
    ports:
      - "${DB_PORT_FW}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_PREFIX}_phpmyadmin
    hostname: ${APP_PREFIX}_phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb

volumes:
  mariadb_data:
