services:
  nginx:
    image: nginx:latest
    container_name: ${APP_PREFIX}_nginx
    hostname: ${APP_PREFIX}_nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_PREFIX}_php
    hostname: ${APP_PREFIX}_php
    volumes:
      - ./:/app
      - ./docker/ssh:/root/.ssh/
      - ./docker/git/.gitconfig:/root/.gitconfig
    working_dir: /app/code